# .github/actions/deploy-ftp/action.yml
name: 'Deploy via FTP'
description: 'Deploy built files to server via FTP, excluding specified files'

inputs:
  build-dir:
    description: 'Path to the build directory'
    required: true
  ftp-server:
    description: 'FTP server address'
    required: true
  ftp-username:
    description: 'FTP username'
    required: true
  ftp-password:
    description: 'FTP password'
    required: true
  ftp-server-dir:
    description: 'Server directory path'
    required: true
  exclude-patterns:
    description: 'Additional exclude patterns (newline separated)'
    required: false
    default: ''
  create-zip:
    description: 'Whether to create a lastest.zip file'
    required: false
    default: 'true'

outputs:
  deploy-success:
    description: 'Whether the deployment was successful'
    value: ${{ steps.deploy-status.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Prepare files for FTP upload
      shell: bash
      run: |
        BUILD_DIR="${{ inputs.build-dir }}"
        echo "[i] Preparing files from: $BUILD_DIR"
        
        mkdir -p upload
        
        rsync -av \
          --exclude="api/config.php" \
          --exclude="*.txt" \
          --exclude="*.md" \
          --exclude="*.log" \
          --exclude="changelog.txt" \
          "$BUILD_DIR/" upload/
        
        echo "[i] Files prepared for upload:"
        find upload -type f | head -20
        TOTAL_FILES=$(find upload -type f | wc -l)
        echo "[i] Total files to upload: $TOTAL_FILES"
        
        TOTAL_SIZE=$(du -sh upload | cut -f1)
        echo "[i] Total upload size: $TOTAL_SIZE"
    
    - name: Create lastest.zip archive
      if: inputs.create-zip == 'true'
      shell: bash
      run: |
        BUILD_DIR="${{ inputs.build-dir }}"
        echo "[i] Creating lastest.zip archive from: $BUILD_DIR"
        
        cd "$BUILD_DIR"
        zip -r lastest.zip . \
          -x "api/config.php" \
          -x "*.txt" \
          -x "*.md" \
          -x "*.log" \
          -x "changelog.txt"
        
        ZIP_SIZE=$(du -sh lastest.zip | cut -f1)
        echo "[i] Created lastest.zip (Size: $ZIP_SIZE)"
        
        echo "[i] Zip file contents preview:"
        unzip -l lastest.zip | head -20
    
    - name: Deploy to server via FTP
      id: deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ inputs.ftp-server }}
        username: ${{ inputs.ftp-username }}
        password: ${{ inputs.ftp-password }}
        local-dir: ./upload/
        server-dir: ${{ inputs.ftp-server-dir }}
        exclude: |
          **/.git*
          **/.git*/**
          **/changelog.txt
          **/*.txt
          **/*.md
          **/*.log
          ${{ inputs.exclude-patterns }}
    
    - name: Set deployment status
      id: deploy-status
      shell: bash
      run: |
        echo "[OK] FTP deployment completed successfully!"
        if [ "${{ inputs.create-zip }}" = "true" ]; then
          echo "[OK] lastest.zip archive uploaded to server root!"
        fi
        echo "success=true" >> $GITHUB_OUTPUT